### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by SkybuckFlying** [crozone/SpectrePoC#26]
crashes and produced a priviled instruction exception, the problem is with p version of tsc.

VS2010/Win7.

There are two instrinsincs, one does not work (only for ring0) other one does work probably for ring 3.

Not sure if I have to set defines myself for proper building, or if code is simply assuming OS access which ofcourse is not the case.

crashes:
#include <intrin.h>   
#include <stdio.h>  
int main()   
{  
 unsigned __int64 i;  
 unsigned int ui;  
 i = __rdtscp(&ui);  
 printf_s("%I64d ticks\n", i);  
 printf_s("TSC_AUX was %x\n", ui);  
}  

works:
// rdtsc.cpp  
// processor: x86, x64  
#include <stdio.h>  
#include <intrin.h>  
  
#pragma intrinsic(__rdtsc)  
  
int main()  
{  
    unsigned __int64 i;  
    i = __rdtsc();  
    printf_s("%I64d ticks\n", i);  
}  

Try make code work in such a way that it uses bottom one always ?

**Comment by SkybuckFlying** [comment]
Seems detection is wrong on AMD X2 3800+.

Problem can be fixed by setting:

#define NORDTSCP

manually.

**Comment by SkybuckFlying** [comment]
(Results on AMD X2 3800+, Win7 Ultimate):

Using a cache hit threshold of 80.
Build: RDTSCP_NOT_SUPPORTED MFENCE_SUPPORTED CLFLUSH_SUPPORTED INTEL_MITIGATION_
DISABLED LINUX_KERNEL_MITIGATION_DISABLED
Reading 40 bytes:
Reading at malicious_x = FFFFE738... Success: 0x54=ÆTÆ score=2
Reading at malicious_x = FFFFE739... Success: 0x68=ÆhÆ score=2
Reading at malicious_x = FFFFE73A... Success: 0x65=ÆeÆ score=2
Reading at malicious_x = FFFFE73B... Success: 0x20=Æ Æ score=2
Reading at malicious_x = FFFFE73C... Success: 0x4D=ÆMÆ score=2
Reading at malicious_x = FFFFE73D... Success: 0x61=ÆaÆ score=2
Reading at malicious_x = FFFFE73E... Success: 0x67=ÆgÆ score=2
Reading at malicious_x = FFFFE73F... Success: 0x69=ÆiÆ score=2
Reading at malicious_x = FFFFE740... Success: 0x63=ÆcÆ score=2
Reading at malicious_x = FFFFE741... Success: 0x20=Æ Æ score=2
Reading at malicious_x = FFFFE742... Success: 0x57=ÆWÆ score=2
Reading at malicious_x = FFFFE743... Success: 0x6F=ÆoÆ score=2
Reading at malicious_x = FFFFE744... Success: 0x72=ÆrÆ score=2
Reading at malicious_x = FFFFE745... Success: 0x64=ÆdÆ score=2
Reading at malicious_x = FFFFE746... Success: 0x73=ÆsÆ score=2
Reading at malicious_x = FFFFE747... Success: 0x20=Æ Æ score=2
Reading at malicious_x = FFFFE748... Success: 0x61=ÆaÆ score=2
Reading at malicious_x = FFFFE749... Success: 0x72=ÆrÆ score=2
Reading at malicious_x = FFFFE74A... Success: 0x65=ÆeÆ score=2
Reading at malicious_x = FFFFE74B... Success: 0x20=Æ Æ score=2
Reading at malicious_x = FFFFE74C... Success: 0x53=ÆSÆ score=2
Reading at malicious_x = FFFFE74D... Success: 0x71=ÆqÆ score=2
Reading at malicious_x = FFFFE74E... Success: 0x75=ÆuÆ score=2
Reading at malicious_x = FFFFE74F... Success: 0x65=ÆeÆ score=2
Reading at malicious_x = FFFFE750... Success: 0x61=ÆaÆ score=2
Reading at malicious_x = FFFFE751... Success: 0x6D=ÆmÆ score=2
Reading at malicious_x = FFFFE752... Success: 0x69=ÆiÆ score=2
Reading at malicious_x = FFFFE753... Success: 0x73=ÆsÆ score=2
Reading at malicious_x = FFFFE754... Success: 0x68=ÆhÆ score=2
Reading at malicious_x = FFFFE755... Success: 0x20=Æ Æ score=2
Reading at malicious_x = FFFFE756... Success: 0x4F=ÆOÆ score=2
Reading at malicious_x = FFFFE757... Success: 0x73=ÆsÆ score=2
Reading at malicious_x = FFFFE758... Success: 0x73=ÆsÆ score=2
Reading at malicious_x = FFFFE759... Success: 0x69=ÆiÆ score=2
Reading at malicious_x = FFFFE75A... Success: 0x66=ÆfÆ score=2
Reading at malicious_x = FFFFE75B... Success: 0x72=ÆrÆ score=2
Reading at malicious_x = FFFFE75C... Success: 0x61=ÆaÆ score=2
Reading at malicious_x = FFFFE75D... Success: 0x67=ÆgÆ score=2
Reading at malicious_x = FFFFE75E... Success: 0x65=ÆeÆ score=2
Reading at malicious_x = FFFFE75F... Success: 0x2E=Æ.Æ score=2

**Comment by crozone** [comment]
Currently we only check for SSE2 support by checking if the compiler has defined `__SSE__` and not `__SSE2__`. We currently don't have any automatic detection of other platform configurations.

**Comment by crozone** [comment]
OK I think I've found your specific issue. We do not currently check for SSE2 support when compiling with MSC. I'll look into adding a case for the MSC compiler so that `NOSSE2` is set when compiling on a pre-SSE2 processor under MSC.

**Comment by crozone** [comment]
Can you please check out PR [27](https://github.com/crozone/SpectrePoC/pull/27) and let me know if it now detects the SSE version on MSC?

**Comment by SkybuckFlying** [comment]
Tried the branch:

'TestTestTest.exe': Loaded 'C:\Junk2\SpectrePoC-msc-sse-detection\SpectrePoC-msc-sse-detection\TestTestTest\Debug\TestTestTest.exe', Symbols loaded.
'TestTestTest.exe': Loaded 'C:\Windows\SysWOW64\ntdll.dll', Cannot find or open the PDB file
'TestTestTest.exe': Loaded 'C:\Windows\SysWOW64\kernel32.dll', Cannot find or open the PDB file
'TestTestTest.exe': Loaded 'C:\Windows\SysWOW64\KernelBase.dll', Cannot find or open the PDB file
'TestTestTest.exe': Loaded 'C:\Windows\SysWOW64\msvcr100d.dll', Symbols loaded.
First-chance exception at 0x0114159e in TestTestTest.exe: 0xC0000096: Privileged instruction.
Unhandled exception at 0x0114159e in TestTestTest.exe: 0xC0000096: Privileged instruction.


#ifndef NORDTSCP
      time1 = __rdtscp( & junk); /* READ TIMER */   CRASHES HERE
      junk = * addr; /* MEMORY ACCESS TO TIME */
      time2 = __rdtscp( & junk) - time1; /* READ TIMER & COMPUTE ELAPSED TIME */
#else

RDTSCP is not allowed on windows.

Only

RDTSC is.

**Comment by SkybuckFlying** [comment]
The weird thing is the P version does work in a ms-dos command prompt and such... but not in the windows gui itself.

**Comment by crozone** [comment]
https://docs.microsoft.com/en-au/cpp/intrinsics/rdtscp?view=vs-2017

Nothing about this instruction appears to be restricted or disallowed in windows applications. Are you running it within a VM?

I'm unnable to reproduce this crash myself for now.
